theme: minima
title: Amazing Omega on GitHub
author: Omega207
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A blog made by Omega207 on GitHub!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Omega207
show_excerpts: true # set to false to remove excerpts on the homepage
